# Generated by Django 3.2.6 on 2021-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(default='Nothing particular to note here.'),
            preserve_default=False,
        ),
    ]
