# Generated by Django 3.2.6 on 2021-08-10 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_entry_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csv_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'], message=['Please select a file having a ".csv" file extension.'])])),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSV file',
                'verbose_name_plural': 'CSV files',
            },
        ),
    ]
