# Generated by Django 3.2.6 on 2021-08-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_csvuploadfile_glossary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='resource',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
