# Generated by Django 3.2.6 on 2021-08-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_entry_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resource',
            field=models.CharField(max_length=250),
        ),
    ]
