# Generated by Django 3.2.6 on 2021-09-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210817_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='glossary_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message=['Please select a file having a ".txt" file extension.'])])),
                ('glossary_title', models.CharField(max_length=250)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Glossary file',
                'verbose_name_plural': 'Glossary files',
            },
        ),
        migrations.DeleteModel(
            name='CsvUploadFile',
        ),
    ]
