# Generated by Django 4.0.5 on 2022-06-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0014_glossaryuploadfile_glossary_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='resources.translation')),
            ],
            options={
                'verbose_name': 'segment',
                'verbose_name_plural': 'segments',
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['title'], name='resources_t_title_bd95e1_idx'),
        ),
    ]
