# Generated by Django 4.0.5 on 2022-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_translation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='title_source',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='title_target',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
