# Generated by Django 4.0.5 on 2022-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_translation_title_source_translation_title_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['job_number'], 'verbose_name': 'translation', 'verbose_name_plural': 'translations'},
        ),
        migrations.RemoveIndex(
            model_name='translation',
            name='resources_t_title_bd95e1_idx',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='title',
            new_name='job_number',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='title_source',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='title_target',
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['job_number'], name='resources_t_job_num_d70b81_idx'),
        ),
    ]
